apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-config
  namespace: dev
data:
  SPRING_PROFILES_ACTIVE: "postgres"
  SERVER_PORT: "8080"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://demo-db:5432/petclinic"
  SPRING_DATASOURCE_USERNAME: "petclinic"
  JAVA_OPTS: "-Xmx256m -Xms128m"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: "DEBUG"
