apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-prod-config
  namespace: prod
data:
  SPRING_PROFILES_ACTIVE: "postgres"
  SERVER_PORT: "8080"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://demo-db-prod:5432/petclinic"
  SPRING_DATASOURCE_USERNAME: "petclinic"
  JAVA_OPTS: "-Xmx512m -Xms256m"
  LOGGING_LEVEL_ROOT: "WARN"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: "INFO"
